version: '3.9'

services:
  db:
    container_name: fit-attendance-db
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '6500:5432'
    environment:
      POSTGRES_DB: fit_attendance
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  app:
    container_name: fit-attendance-app
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
